-- 添加缺少的列到 live_accounts 表
ALTER TABLE live_accounts
ADD COLUMN IF NOT EXISTS account_code VARCHAR(100),
ADD COLUMN IF NOT EXISTS platform VARCHAR(50),
ADD COLUMN IF NOT EXISTS location VARCHAR(100),
ADD COLUMN IF NOT EXISTS start_time TIMESTAMP,
ADD COLUMN IF NOT EXISTS end_time TIMESTAMP,
ADD COLUMN IF NOT EXISTS total_hosts INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS main_hosts INTEGER[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES users(id),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP; 